vim.api.nvim_set_keymap("n", "<space>fdj<space>", "f<CR>", {})
vim.api.nvim_set_keymap("v", "<space>fdj<space>", "f<CR>", {})
vim.api.nvim_set_keymap("n", "<space>fdi<space>", "f<BS>", {})
vim.api.nvim_set_keymap("v", "<space>fdi<space>", "f<BS>", {})
vim.api.nvim_set_keymap("n", "<space>fdk<space>", ":Hi + ", {})
vim.api.nvim_set_keymap("v", "<space>fdk<space>", "<C-U>:Hi + ", {})
vim.api.nvim_set_keymap("n", "<space>fdl<space>", "f<C-L>", {})
vim.api.nvim_set_keymap("n", "<space>fdu<space>", "<Cmd>Hi<<CR>", {})
vim.api.nvim_set_keymap("n", "<space>fdo<space>", "<Cmd>Hi><CR>", {})
vim.api.nvim_set_keymap("n", "<space>fdU<space>", "<Cmd>Hi{<CR>", {})
vim.api.nvim_set_keymap("n", "<space>fdO<space>", "<Cmd>Hi}<CR>", {})
